import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/nav/navbar'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={clsx(inter.className, 'bg-gray-100 min-h-screen')}>
				<main className='mx-auto max-w-[1400px] bg-white'>
					<Navbar />
					{children}
				</main>
			</body>
		</html>
	)
}
